title: Joseph Noonan 
description: Portfolio and Projects 
url: https://noonan-portfolio.github.io
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap



locale: en
markdown: kramdown



  
